parameters:

imports:
    - { resource: services/commandbus.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DevSesame\Shared\Infrastructure\:
        resource: '../src/Shared/Infrastructure/*'

    DevSesame\Signings\Application\:
        resource: '../src/Signings/Application'
        exclude: '../src/Signings/Application/{Command}'

    DevSesame\Signings\Infrastructure\EntryPoint\Controller\:
        resource: '../src/Signings/Infrastructure/EntryPoint/Controller'
        tags: [ 'controller.service_arguments' ]

    DevSesame\Signings\Domain\Repository\UserRepository:
        class: 'DevSesame\Signings\Infrastructure\Repository\Persistence\MysqlUserRepository'
        arguments: [ '@doctrine.orm.entity_manager' ]

    DevSesame\Signings\Domain\Repository\WorkEntryRepository:
        class: 'DevSesame\Signings\Infrastructure\Repository\Persistence\MysqlEntryWorkRepository'
        arguments: [ '@doctrine.orm.entity_manager' ]

    DevSesame\Signings\Domain\Service\JWTDecoder:
        arguments:
            - '%env(resolve:JWT_SECRET)%'
